(()=>{
const SUPABASE_URL='https://nbsmkxarkpesjiftmbwm.supabase.co';
const SUPABASE_KEY='sb_publishable_dMXeVPXD_oU5NrdV2-sSew_CZxB5lFI';
const DEFAULT_WA='6287878333037';
let db,services=[],sizes=[],motors=[],prices=[],waNumber=DEFAULT_WA,reloadTimer;
let selectedMotor=null,selectedService=null,selectedSize=null,selectedPrice=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const rupiah=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)||0);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const findPrice=(serviceId,sizeId)=>{const p=prices.find(x=>x.service_id===serviceId&&x.motor_size_id===sizeId&&x.active!==false);return p?Number(p.price):null};
async function loadSdk(){if(window.supabase?.createClient)return;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>window.supabase?.createClient?ok():no(new Error('Supabase SDK tidak tersedia'));s.onerror=()=>no(new Error('Gagal memuat Supabase'));document.head.appendChild(s)})}
function renderPublicServices(){const box=document.querySelector('.services');if(!box)return;box.innerHTML=services.length?services.map(s=>{const body=`<h3>${esc(s.name)}</h3><p>${esc(s.description||'')}</p>`;return s.result_url?`<a class="service service-link" href="${esc(s.result_url)}" target="_blank" rel="noopener noreferrer">${body}</a>`:`<div class="service">${body}</div>`}).join(''):'<div class="service"><h3>Belum ada layanan aktif</h3><p>Silakan cek kembali nanti.</p></div>'}
function renderPublicPrices(){const section=$('pricelist'),buttons=section?.querySelector('.size-buttons'),table=$('priceTable');if(!buttons||!table)return;buttons.innerHTML=sizes.map((s,i)=>`<button class="size-btn${i===0?' active':''}" data-size-id="${esc(s.id)}" type="button">${esc(s.name)}</button>`).join('');const show=id=>{const size=sizes.find(s=>s.id===id)||sizes[0];if(!size){table.innerHTML='<p class="note">Belum ada size motor.</p>';return}table.innerHTML=`<h3>${esc(size.name)} Motorcycle</h3><div class="pricegrid">${services.map(s=>{const p=findPrice(s.id,size.id);return `<div class="priceitem"><span>${esc(s.name)}</span><b>${p==null?'Belum tersedia':rupiah(p)}</b></div>`}).join('')}</div>`;buttons.querySelectorAll('.size-btn').forEach(b=>b.classList.toggle('active',b.dataset.sizeId===size.id))};buttons.querySelectorAll('.size-btn').forEach(b=>b.onclick=()=>show(b.dataset.sizeId));show(sizes[0]?.id)}
function bookingStyles(){if($('tmd-booking-v6-styles'))return;const s=document.createElement('style');s.id='tmd-booking-v6-styles';s.textContent=`.tmd6-modal{position:fixed;inset:0;background:rgba(15,23,42,.68);display:none;align-items:flex-end;justify-content:center;padding:12px;z-index:99999}.tmd6-modal.open{display:flex}.tmd6-box{width:min(680px,100%);max-height:94vh;overflow:auto;background:#fff;border-radius:22px;padding:20px;box-shadow:0 20px 70px #0006}.tmd6-head{display:flex;justify-content:space-between;align-items:center}.tmd6-head h2{margin:0}.tmd6-close{border:0;background:#eef2f7;border-radius:10px;width:40px;height:40px;font-size:22px}.tmd6-step{margin-top:16px}.tmd6-title{font-size:14px;font-weight:900;color:#0757d9;margin-bottom:7px}.tmd6-field{margin-bottom:13px}.tmd6-field input,.tmd6-field select,.tmd6-field textarea{width:100%;padding:12px;border:1px solid #dbe2ef;border-radius:11px;font:inherit}.tmd6-results{display:grid;gap:8px;margin-top:8px;max-height:300px;overflow:auto}.tmd6-result{border:1px solid #e5e7eb;border-radius:14px;padding:12px;cursor:pointer}.tmd6-result:hover,.tmd6-result.selected{border-color:#0757d9;background:#eff6ff}.tmd6-name{font-weight:900}.tmd6-pill{display:inline-block;background:#eaf1ff;color:#0757d9;border-radius:999px;padding:4px 8px;font-size:11px;font-weight:800;margin-top:5px}.tmd6-mini{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.tmd6-mini div{font-size:11px;border-top:1px solid #edf0f5;padding-top:5px;display:flex;justify-content:space-between}.tmd6-mini b,.tmd6-price{color:#0757d9}.tmd6-selected{border:1px solid #bfdbfe;background:#eff6ff;border-radius:15px;padding:14px}.tmd6-price{font-size:20px;font-weight:900;margin-top:7px}.tmd6-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.tmd6-submit{width:100%;border:0;background:#16a34a;color:#fff;padding:14px;border-radius:12px;font-weight:900}.tmd6-error{display:none;background:#fef2f2;color:#b91c1c;border-radius:10px;padding:10px;margin-top:10px}.tmd6-error.show{display:block}.tmd6-hint{font-size:11px;color:#6b7280;margin-top:6px}@media(max-width:520px){.tmd6-grid{grid-template-columns:1fr}.tmd6-modal{padding:0}.tmd6-box{border-radius:22px 22px 0 0}.tmd6-mini{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function modalMarkup(){return `<div id="tmdBookingModalV6" class="tmd6-modal"><div class="tmd6-box"><div class="tmd6-head"><h2>Booking Treatment</h2><button id="tmd6Close" class="tmd6-close" type="button">×</button></div><p style="color:#6b7280;font-size:12px">Nama → cari tipe motor → pilih treatment → tanggal & jam → nomor HP → kondisi motor.</p><div id="tmd6Error" class="tmd6-error"></div><form id="tmd6Form"><div class="tmd6-step"><div class="tmd6-title">1. Nama customer</div><div class="tmd6-field"><input id="tmd6Name" required maxlength="80" placeholder="Nama customer"></div></div><div class="tmd6-step"><div class="tmd6-title">2. Cari tipe motor</div><div class="tmd6-field"><input id="tmd6Motor" required autocomplete="off" placeholder="Ketik contoh: Beat, Vario 125, NMAX, PCX 160..."><div id="tmd6Results" class="tmd6-results"></div><div class="tmd6-hint">Pencarian toleran terhadap spasi, tanda hubung, dan nama seri. Contoh: NMAX tetap menemukan N Max.</div></div></div><div id="tmd6TreatmentStep" class="tmd6-step" hidden><div class="tmd6-title">3. Pilih treatment</div><select id="tmd6Treatment" required><option value="">Pilih treatment...</option></select><div id="tmd6Selected" class="tmd6-selected" style="margin-top:10px"></div></div><div id="tmd6ScheduleStep" class="tmd6-step" hidden><div class="tmd6-title">4. Waktu & tanggal booking</div><div class="tmd6-grid"><div class="tmd6-field"><label>Tanggal</label><input id="tmd6Date" type="date" required></div><div class="tmd6-field"><label>Jam</label><select id="tmd6Time" required><option value="">Pilih jam...</option></select></div></div></div><div id="tmd6ContactStep" class="tmd6-step" hidden><div class="tmd6-title">5. No. HP / WhatsApp</div><div class="tmd6-field"><input id="tmd6Phone" type="tel" required placeholder="08xxxxxxxxxx"></div></div><div id="tmd6NotesStep" class="tmd6-step" hidden><div class="tmd6-title">6. Deskripsi kondisi motor (opsional)</div><div class="tmd6-field"><textarea id="tmd6Notes" rows="4" maxlength="1000" placeholder="Contoh: body banyak swirl, ada baret di tangki, dll."></textarea></div></div><button id="tmd6Submit" class="tmd6-submit" type="submit" hidden>Lanjut Booking via WhatsApp</button></form></div></div>`}
const slots=()=>{const a=[];for(let h=9;h<=18;h++)for(const m of [0,30]){if(h===18&&m===30)continue;a.push(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`)}return a};
const step=(id,on)=>{const e=$(id);if(e)e.hidden=!on};
const showError=m=>{const e=$('tmd6Error');if(e){e.textContent=m||'';e.classList.toggle('show',!!m)}};
function normalizeSearch(v){return String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function compactSearch(v){return normalizeSearch(v).replace(/\s+/g,'')}
function searchScore(m,q){const qn=normalizeSearch(q),qc=compactSearch(q);if(!qc)return 0;const full=normalizeSearch(`${m.brand} ${m.model}`),model=normalizeSearch(m.model),brand=normalizeSearch(m.brand),compact=full.replace(/\s/g,'');let score=0;if(full===qn)score+=10000;if(model===qn)score+=9500;if(compact===qc)score+=9300;if(model.startsWith(qn))score+=8000;if(brand.startsWith(qn))score+=7600;if(model.includes(qn))score+=6500;if(compact.includes(qc))score+=6200;const qt=qn.split(' ').filter(Boolean),tokens=full.split(' ').filter(Boolean);if(qt.length){let matched=0;for(const t of qt){if(tokens.some(x=>x===t))matched++;else if(tokens.some(x=>x.startsWith(t)||x.includes(t)))matched+=0.6}if(matched===qt.length)score+=6000+matched*100;else score+=matched*500}return score}
function renderResults(q){const box=$('tmd6Results');if(!box)return;const raw=String(q||'').trim();if(raw.length<2){box.innerHTML='';return}const scored=motors.map(m=>({m,score:searchScore(m,raw)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||String(a.m.brand+' '+a.m.model).localeCompare(String(b.m.brand+' '+b.m.model),'id'));const hits=scored.slice(0,60).map(x=>x.m);if(!hits.length){box.innerHTML='<div style="color:#6b7280;font-size:12px">Motor tidak ditemukan di katalog aktif.</div>';return}box.innerHTML=hits.map(m=>{const size=sizes.find(s=>s.id===m.motor_size_id);const rows=services.map(s=>{const p=findPrice(s.id,m.motor_size_id);return `<div><span>${esc(s.name)}</span><b>${p==null?'-':rupiah(p)}</b></div>`}).join('');return `<div class="tmd6-result" data-id="${esc(m.id)}"><div class="tmd6-name">${esc(m.brand)} ${esc(m.model)}</div><span class="tmd6-pill">Size: ${esc(size?.name||'-')}</span><div class="tmd6-mini">${rows}</div></div>`}).join('');box.querySelectorAll('.tmd6-result').forEach(e=>e.onclick=()=>selectMotor(e.dataset.id))}
function selectMotor(id){selectedMotor=motors.find(m=>m.id===id)||null;selectedSize=selectedMotor?sizes.find(s=>s.id===selectedMotor.motor_size_id):null;selectedService=null;selectedPrice=null;if(!selectedMotor)return;$('tmd6Motor').value=`${selectedMotor.brand} ${selectedMotor.model}`;$('tmd6Treatment').innerHTML='<option value="">Pilih treatment...</option>'+services.map(s=>{const p=findPrice(s.id,selectedMotor.motor_size_id);return `<option value="${esc(s.id)}"${p==null?' disabled':''}>${esc(s.name)} — ${p==null?'Harga belum tersedia':rupiah(p)}</option>`}).join('');$('tmd6Selected').innerHTML=`<b>${esc(selectedMotor.brand)} ${esc(selectedMotor.model)}</b><div><span class="tmd6-pill">Size: ${esc(selectedSize?.name||'-')}</span></div><p style="margin:8px 0 0;color:#6b7280;font-size:12px">Pilih treatment untuk melihat harga.</p>`;step('tmd6TreatmentStep',true);step('tmd6ScheduleStep',false);step('tmd6ContactStep',false);step('tmd6NotesStep',false);$('tmd6Submit').hidden=true}
function selectTreatment(id){selectedService=services.find(s=>s.id===id)||null;selectedPrice=selectedService&&selectedMotor?findPrice(selectedService.id,selectedMotor.motor_size_id):null;$('tmd6Selected').innerHTML=`<b>${esc(selectedMotor?.brand||'')} ${esc(selectedMotor?.model||'')}</b><div><span class="tmd6-pill">Size: ${esc(selectedSize?.name||'-')}</span> <span class="tmd6-pill">Treatment: ${esc(selectedService?.name||'-')}</span></div><div class="tmd6-price">${selectedPrice==null?'Harga belum tersedia':rupiah(selectedPrice)}</div>`;const ok=!!selectedService&&selectedPrice!=null;step('tmd6ScheduleStep',ok);step('tmd6ContactStep',ok);step('tmd6NotesStep',ok);$('tmd6Submit').hidden=!ok}
async function submit(e){e.preventDefault();showError('');if(!selectedMotor||!selectedService||selectedPrice==null)return showError('Pilih motor dan treatment dulu.');const name=$('tmd6Name').value.trim(),date=$('tmd6Date').value,time=$('tmd6Time').value,phone=$('tmd6Phone').value.trim(),notes=$('tmd6Notes').value.trim();if(!name||!date||!time||!phone)return showError('Lengkapi data wajib dulu.');if(!/^[0-9+\s()-]{8,30}$/.test(phone))return showError('Nomor HP/WhatsApp tidak valid.');if(date<today())return showError('Tanggal booking tidak boleh lewat.');const btn=$('tmd6Submit');btn.disabled=true;btn.textContent='Menyimpan booking...';try{const r=await db.from('bookings').insert({customer_name:name,phone,motor_type:`${selectedMotor.brand} ${selectedMotor.model}`,service_id:selectedService.id,motor_size_id:selectedMotor.motor_size_id,appointment_date:date,appointment_time:time,dp_amount:null,notes:notes||null,dp_paid:false,status:'pending',source:'whatsapp'});if(r.error)throw r.error;const msg=['Halo THE MOTODETAILERS, saya mau booking treatment.','',`Nama: ${name}`,`Tipe motor: ${selectedMotor.brand} ${selectedMotor.model}`,`Size motor: ${selectedSize?.name||'-'}`,`Treatment: ${selectedService.name}`,`Harga: ${rupiah(selectedPrice)}`,`Tanggal: ${date}`,`Jam: ${time}`,`No. HP: ${phone}`,notes?`Deskripsi kondisi motor: ${notes}`:''].filter(Boolean).join('\n');location.href=`https://wa.me/${waNumber}?text=${encodeURIComponent(msg)}`}catch(e){console.error(e);showError(e?.message||'Booking gagal disimpan');btn.disabled=false;btn.textContent='Lanjut Booking via WhatsApp'}}
function initBooking(){const old=document.querySelector('.booking-button');if(!old)return;bookingStyles();document.getElementById('tmdBookingModalV6')?.remove();old.replaceWith(old.cloneNode(true));const btn=document.querySelector('.booking-button');btn.href='#booking';btn.removeAttribute('target');btn.removeAttribute('rel');document.body.insertAdjacentHTML('beforeend',modalMarkup());const modal=$('tmdBookingModalV6');btn.onclick=e=>{e.preventDefault();modal.classList.add('open');$('tmd6Name').focus()};$('tmd6Close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};$('tmd6Time').innerHTML='<option value="">Pilih jam...</option>'+slots().map(t=>`<option value="${t}">${t}</option>`).join('');const d=$('tmd6Date');d.min=today();d.value=today();$('tmd6Motor').oninput=e=>{selectedMotor=null;selectedService=null;selectedPrice=null;step('tmd6TreatmentStep',false);step('tmd6ScheduleStep',false);step('tmd6ContactStep',false);step('tmd6NotesStep',false);$('tmd6Submit').hidden=true;renderResults(e.target.value)};$('tmd6Treatment').onchange=e=>selectTreatment(e.target.value);$('tmd6Form').onsubmit=submit}
async function fetchData(){const[s,z,m,p,settings]=await Promise.all([db.from('services').select('id,name,slug,description,result_url,image_url,active,sort_order').eq('active',true).order('sort_order'),db.from('motor_sizes').select('id,name,active,sort_order').eq('active',true).order('sort_order'),db.from('motor_catalog').select('id,brand,model,motor_size_id,active,sort_order').eq('active',true).order('brand').order('sort_order').limit(5000),db.from('service_prices').select('id,service_id,motor_size_id,price,active').eq('active',true),db.from('site_settings').select('setting_key,setting_value')]);for(const r of [s,z,m,p,settings])if(r.error)throw r.error;services=s.data||[];sizes=z.data||[];motors=m.data||[];prices=p.data||[];const st=Object.fromEntries((settings.data||[]).map(x=>[x.setting_key,x.setting_value]));const wa=st.whatsapp?.url||'';const match=String(wa).match(/wa\.me\/(\d+)/);if(match)waNumber=match[1]}
function renderAll(){renderPublicServices();renderPublicPrices();if(!document.getElementById('tmdBookingModalV6'))initBooking()}
function scheduleReload(){clearTimeout(reloadTimer);reloadTimer=setTimeout(()=>fetchData().then(renderAll).catch(e=>console.error('[TMD] realtime reload',e)),250)}
function subscribeRealtime(){db.channel('customer-live-sync-v6').on('postgres_changes',{event:'*',schema:'public',table:'service_prices'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'services'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'motor_catalog'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'motor_sizes'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'site_settings'},scheduleReload).subscribe()}
async function init(){const box=document.querySelector('.services');if(box)box.innerHTML='<div class="service"><h3>Memuat layanan...</h3><p>Mengambil data layanan terbaru.</p></div>';try{await loadSdk();db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);await fetchData();renderAll();subscribeRealtime()}catch(e){console.error('[TMD] public sync',e);if(box)box.innerHTML='<div class="service"><h3>Layanan belum dapat dimuat</h3><p>Silakan refresh halaman.</p></div>';}}
function fixPublicSearchLayout(){
 const box=document.querySelector('.searchbox'),results=document.getElementById('results');
 if(!box||!results)return;
 const noteId='tmd-public-search-note';
 let note=document.getElementById(noteId);
 if(!note){
   note=document.createElement('p');
   note.id=noteId;
   note.className='note';
   note.textContent='Ketik minimal 2 karakter untuk mencari.';
   box.insertBefore(note,results);
 }
 results.querySelectorAll('.note').forEach(n=>n.remove());
 if(!document.getElementById('tmd-public-search-layout-fix')){
   const s=document.createElement('style');s.id='tmd-public-search-layout-fix';
   s.textContent=`
   .searchbox{position:relative}
   .searchbox #tmd-public-search-note{display:block;margin:8px 0 0}
   .searchbox .results{position:relative;left:auto;right:auto;top:auto;margin-top:12px;max-height:360px;overflow:auto;z-index:auto;padding:0}
   .searchbox .results:empty{display:none}
   .searchbox .results .result{box-shadow:0 8px 24px rgba(0,0,0,.08)}
   `;
   document.head.appendChild(s);
 }
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{fixPublicSearchLayout();init()},{once:true});else{fixPublicSearchLayout();init()}
})();