(()=>{
'use strict';
const URL='https://nbsmkxarkpesjiftmbwm.supabase.co',KEY='sb_publishable_dMXeVPXD_oU5NrdV2-sSew_CZxB5lFI';
let db,services=[],sizes=[],motors=[],prices=[],portfolio=[],timer;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)||0);
const norm=v=>String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const publicUrl=path=>path?`${URL}/storage/v1/object/public/tmd-portfolio/${String(path).split('/').map(encodeURIComponent).join('/')}`:'';
const findPrice=(sid,zid)=>{const p=prices.find(x=>x.service_id===sid&&x.motor_size_id===zid&&x.active!==false);return p?Number(p.price):null};
function addPortfolioStyles(){if(document.getElementById('tmdPortfolioStyles'))return;const s=document.createElement('style');s.id='tmdPortfolioStyles';s.textContent=`
#hasil-pekerjaan{margin-top:30px;background:#fff;padding:20px;border-radius:18px;box-shadow:0 5px 18px rgba(0,0,0,.06);border:1px solid #e5e7eb}
.tmd-portfolio-head{display:flex;justify-content:space-between;align-items:end;gap:12px;flex-wrap:wrap}.tmd-portfolio-head h2{margin:0}.tmd-portfolio-filter{display:flex;gap:8px;overflow:auto;padding:12px 0 4px}.tmd-portfolio-filter button{border:1px solid #dbe5ff;background:#f4f7ff;color:#0757d9;padding:9px 12px;border-radius:10px;font-weight:800;white-space:nowrap;cursor:pointer}.tmd-portfolio-filter button.active{background:#0757d9;color:#fff}.tmd-portfolio-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:12px}.tmd-portfolio-card{border:1px solid #e5e7eb;border-radius:15px;overflow:hidden;background:#fff;cursor:pointer}.tmd-portfolio-media{aspect-ratio:4/3;background:#eef3fb;display:flex;align-items:center;justify-content:center;overflow:hidden;position:relative}.tmd-portfolio-media img,.tmd-portfolio-media video{width:100%;height:100%;object-fit:cover;display:block}.tmd-portfolio-play{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:48px;height:48px;border-radius:50%;background:#0757d9;color:#fff;display:flex;align-items:center;justify-content:center;font-size:22px;box-shadow:0 8px 24px #0004}.tmd-portfolio-ba{display:grid;grid-template-columns:1fr 1fr;width:100%;height:100%;gap:2px}.tmd-portfolio-ba>div{position:relative;overflow:hidden}.tmd-portfolio-ba img{width:100%;height:100%;object-fit:cover}.tmd-portfolio-label{position:absolute;left:7px;top:7px;background:#111827cc;color:#fff;border-radius:7px;padding:4px 7px;font-size:11px;font-weight:800}.tmd-portfolio-info{padding:11px 12px}.tmd-portfolio-info strong{display:block;color:#0757d9;font-size:16px}.tmd-portfolio-info span{display:block;color:#6b7280;font-size:12px;margin-top:4px}.tmd-portfolio-modal{position:fixed;inset:0;background:#000c;z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px}.tmd-portfolio-modal-box{width:min(900px,100%);max-height:92vh;background:#111827;border-radius:18px;overflow:auto;position:relative}.tmd-portfolio-modal-close{position:absolute;right:10px;top:10px;width:38px;height:38px;border:0;border-radius:50%;background:#fff;color:#111827;font-size:24px;cursor:pointer;z-index:2}.tmd-portfolio-modal-media{padding:12px}.tmd-portfolio-modal-media img,.tmd-portfolio-modal-media video{display:block;width:100%;max-height:78vh;object-fit:contain;border-radius:12px;background:#000}.tmd-portfolio-modal-info{color:#fff;padding:0 16px 16px}.tmd-portfolio-modal-info strong{font-size:18px}.tmd-portfolio-modal-info p{color:#d1d5db;line-height:1.5;margin:6px 0 0}.tmd-portfolio-empty{padding:24px 8px;text-align:center;color:#6b7280}
@media(max-width:600px){.tmd-portfolio-grid{grid-template-columns:1fr 1fr}.tmd-portfolio-card{border-radius:13px}.tmd-portfolio-info{padding:9px}.tmd-portfolio-info strong{font-size:14px}}
`;document.head.appendChild(s)}
async function loadSdk(){if(window.supabase?.createClient)return;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
async function fetchData(){
 const [s,z,m,p,pm]=await Promise.all([
  db.from('services').select('id,name,slug,description,result_url,image_url,active,sort_order').eq('active',true).order('sort_order').order('name'),
  db.from('motor_sizes').select('id,name,active,sort_order').eq('active',true).order('sort_order').order('name'),
  db.from('motor_catalog').select('id,brand,model,motor_size_id,active,sort_order').eq('active',true).order('brand').order('sort_order').limit(5000),
  db.from('service_prices').select('id,service_id,motor_size_id,price,active').eq('active',true),
  db.from('portfolio_media').select('id,service_id,media_type,display_mode,title,description,storage_path,before_path,after_path,active,sort_order,created_at').eq('active',true).order('sort_order').order('created_at',{ascending:false})
 ]);
 for(const r of [s,z,m,p,pm])if(r.error)throw r.error;
 services=s.data||[];sizes=z.data||[];motors=m.data||[];prices=p.data||[];portfolio=pm.data||[];
}
function neutralizeLegacyServiceLinks(){document.querySelectorAll('.services .service-link').forEach(a=>{a.href='#hasil-pekerjaan';a.removeAttribute('target');a.removeAttribute('rel')})}
function renderServices(){const box=document.querySelector('.services');if(!box)return;box.innerHTML=services.length?services.map(s=>{const body=`<h3>${esc(s.name)}</h3><p>${esc(s.description||'')}</p>`;return `<a class="service service-link" href="#hasil-pekerjaan" data-service-id="${esc(s.id)}">${body}</a>`}).join(''):'<div class="service"><h3>Belum ada layanan aktif</h3><p>Silakan cek kembali nanti.</p></div>'}
function ensurePortfolioSection(){let section=$('hasil-pekerjaan');if(section)return section;const searchbox=$('katalog');if(!searchbox)return null;section=document.createElement('section');section.id='hasil-pekerjaan';section.innerHTML='<div class="tmd-portfolio-head"><div><h2 class="section-title">Hasil Pekerjaan</h2><p class="note">Lihat hasil foto dan video treatment The Motodetailers.</p></div></div><div id="tmdPortfolioFilter" class="tmd-portfolio-filter"></div><div id="tmdPortfolioGrid" class="tmd-portfolio-grid"></div>';searchbox.parentNode.insertBefore(section,searchbox);return section}
let portfolioFilter='all';
function renderPortfolio(){addPortfolioStyles();const section=ensurePortfolioSection();if(!section)return;const filter=$('tmdPortfolioFilter'),grid=$('tmdPortfolioGrid');if(!filter||!grid)return;filter.innerHTML=`<button type="button" data-pf="all" class="${portfolioFilter==='all'?'active':''}">Semua</button>`+services.map(s=>`<button type="button" data-pf="${esc(s.id)}" class="${portfolioFilter===s.id?'active':''}">${esc(s.name)}</button>`).join('');const rows=portfolio.filter(x=>portfolioFilter==='all'||x.service_id===portfolioFilter);if(!rows.length){grid.innerHTML='<div class="tmd-portfolio-empty" style="grid-column:1/-1">Belum ada hasil pekerjaan untuk layanan ini.</div>';return}grid.innerHTML=rows.map(x=>{const service=services.find(s=>s.id===x.service_id),name=service?.name||'Layanan';if(x.display_mode==='before_after'){return `<article class="tmd-portfolio-card" data-media-id="${x.id}"><div class="tmd-portfolio-media"><div class="tmd-portfolio-ba"><div><img src="${esc(publicUrl(x.before_path))}" alt="${esc(x.title)} before"><span class="tmd-portfolio-label">BEFORE</span></div><div><img src="${esc(publicUrl(x.after_path))}" alt="${esc(x.title)} after"><span class="tmd-portfolio-label">AFTER</span></div></div></div><div class="tmd-portfolio-info"><strong>${esc(x.title)}</strong><span>${esc(name)} · Before / After</span></div></article>`}const src=publicUrl(x.storage_path);const media=x.media_type==='video'?`<video src="${esc(src)}" muted playsinline preload="metadata"></video><span class="tmd-portfolio-play">▶</span>`:`<img src="${esc(src)}" alt="${esc(x.title)}" loading="lazy">`;return `<article class="tmd-portfolio-card" data-media-id="${x.id}"><div class="tmd-portfolio-media">${media}</div><div class="tmd-portfolio-info"><strong>${esc(x.title)}</strong><span>${esc(name)}${x.media_type==='video'?' · Video':' · Foto'}</span></div></article>`}).join('')}
function openPortfolioModal(id){const x=portfolio.find(p=>p.id===id);if(!x)return;const service=services.find(s=>s.id===x.service_id),name=service?.name||'Layanan';let media='';if(x.display_mode==='before_after')media=`<div class="tmd-portfolio-ba" style="height:min(70vh,650px)"><div><img src="${esc(publicUrl(x.before_path))}" alt="${esc(x.title)} before"><span class="tmd-portfolio-label">BEFORE</span></div><div><img src="${esc(publicUrl(x.after_path))}" alt="${esc(x.title)} after"><span class="tmd-portfolio-label">AFTER</span></div></div>`;else if(x.media_type==='video')media=`<video src="${esc(publicUrl(x.storage_path))}" controls playsinline preload="metadata"></video>`;else media=`<img src="${esc(publicUrl(x.storage_path))}" alt="${esc(x.title)}">`;const wrap=document.createElement('div');wrap.className='tmd-portfolio-modal';wrap.innerHTML=`<div class="tmd-portfolio-modal-box"><button class="tmd-portfolio-modal-close" type="button" aria-label="Tutup">×</button><div class="tmd-portfolio-modal-media">${media}</div><div class="tmd-portfolio-modal-info"><strong>${esc(x.title)}</strong><div>${esc(name)}</div>${x.description?`<p>${esc(x.description)}</p>`:''}</div></div>`;wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('.tmd-portfolio-modal-close'))wrap.remove()});document.body.appendChild(wrap)}
function bindPortfolio(){if(document.body.dataset.tmdPortfolioBound==='1')return;document.body.dataset.tmdPortfolioBound='1';document.addEventListener('click',e=>{const f=e.target.closest('[data-pf]');if(f){portfolioFilter=f.dataset.pf||'all';renderPortfolio();return}const card=e.target.closest('.tmd-portfolio-card');if(card){openPortfolioModal(card.dataset.mediaId);return}const serviceLink=e.target.closest('.services .service-link[data-service-id]');if(serviceLink){e.preventDefault();portfolioFilter=serviceLink.dataset.serviceId;renderPortfolio();document.getElementById('hasil-pekerjaan')?.scrollIntoView({behavior:'smooth',block:'start'})}})}
function renderPrices(){const section=$('pricelist');if(!section)return;const buttons=section.querySelector('.size-buttons'),table=$('priceTable');if(!buttons||!table)return;const current=buttons.querySelector('.size-btn.active')?.dataset.sizeId||buttons.querySelector('.size-btn.active')?.dataset.size;buttons.innerHTML=sizes.map((s,i)=>`<button class="size-btn${(current===s.id||current===s.name||(!current&&i===0))?' active':''}" data-size-id="${esc(s.id)}" type="button">${esc(s.name)}</button>`).join('');const show=id=>{const z=sizes.find(x=>x.id===id)||sizes.find(x=>x.name===id)||sizes[0];if(!z){table.innerHTML='<p class="note">Belum ada size motor.</p>';return}table.innerHTML=`<h3>${esc(z.name)} Motorcycle</h3><div class="pricegrid">${services.map(s=>{const p=findPrice(s.id,z.id);return `<div class="priceitem"><span>${esc(s.name)}</span><b>${p==null?'Belum tersedia':money(p)}</b></div>`}).join('')}</div>`;buttons.querySelectorAll('.size-btn').forEach(b=>b.classList.toggle('active',b.dataset.sizeId===z.id))};buttons.querySelectorAll('.size-btn').forEach(b=>b.onclick=()=>show(b.dataset.sizeId));show(current||sizes[0]?.id)}
function score(m,q){const n=norm(q),c=n.replace(/\s/g,''),full=norm(`${m.brand} ${m.model}`),model=norm(m.model),brand=norm(m.brand),compact=full.replace(/\s/g,'');let x=0;if(full===n)x+=10000;if(model===n)x+=9500;if(compact===c)x+=9000;if(model.startsWith(n))x+=8000;if(model.includes(n))x+=6500;if(compact.includes(c))x+=6000;if(brand.startsWith(n))x+=3000;return x}
function bindSearch(){const input=$('search'),box=$('results');if(!input||!box)return;const render=q=>{q=String(q||'').trim();if(q.length<2){box.innerHTML='<p class="note">Ketik minimal 2 karakter untuk mencari.</p>';return}const hits=motors.map(m=>({m,x:score(m,q)})).filter(a=>a.x>0).sort((a,b)=>b.x-a.x).slice(0,50).map(a=>a.m);if(!hits.length){box.innerHTML='<div class="result"><strong>Motor tidak ditemukan.</strong><div class="note">Coba ketik nama model lain.</div></div>';return}box.innerHTML=hits.map(m=>{const z=sizes.find(s=>s.id===m.motor_size_id);const rows=services.map(s=>{const p=findPrice(s.id,m.motor_size_id);return `<div class="priceitem"><span>${esc(s.name)}</span><b>${p==null?'Belum tersedia':money(p)}</b></div>`}).join('');return `<div class="result"><strong>${esc(m.brand)} ${esc(m.model)}</strong><span class="pill">${esc(z?.name||'-')}</span><div style="margin-top:10px">${rows}</div></div>`}).join('')};input.oninput=e=>render(e.target.value);render(input.value)}
function renderAll(){neutralizeLegacyServiceLinks();renderServices();renderPrices();bindSearch();renderPortfolio();bindPortfolio()}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>fetchData().then(renderAll).catch(e=>console.error('[TMD public v3]',e)),300)}
function subscribe(){db.channel('tmd-public-v3').on('postgres_changes',{event:'*',schema:'public',table:'services'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'service_prices'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'portfolio_media'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'motor_catalog'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'motor_sizes'},schedule).subscribe();setInterval(()=>{if(document.visibilityState==='visible')schedule()},5000)}
async function init(){try{addPortfolioStyles();neutralizeLegacyServiceLinks();await loadSdk();db=supabase.createClient(URL,KEY);await fetchData();renderAll();subscribe()}catch(e){console.error('[TMD public v3]',e);neutralizeLegacyServiceLinks();const box=document.querySelector('.services');if(box)box.innerHTML='<div class="service"><h3>Data belum dapat dimuat</h3><p>Silakan refresh halaman.</p></div>';const t=$('priceTable');if(t)t.innerHTML='<p class="note">Pricelist belum dapat dimuat.</p>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
