const SUPABASE_URL = 'https://nbsmkxarkpesjiftmbwm.supabase.co';
const SUPABASE_KEY = 'sb_publishable_dMXeVPXD_oU5NrdV2-sSew_CZxB5lFI';
const ADMIN_EMAIL = 'taufikzainalmutakin@gmail.com';
const ACCESS_COOKIE = 'tmd_admin_access';
const REFRESH_COOKIE = 'tmd_admin_refresh';
const ACCESS_MAX_AGE = 15 * 60;
const REFRESH_MAX_AGE = 7 * 24 * 60 * 60;
function parseCookies(request){const raw=request.headers.get('Cookie')||'';const out={};for(const part of raw.split(';')){const i=part.indexOf('=');if(i<0)continue;out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Strict`}
function clearCookie(name){return `${name}=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Strict`}
function securityHeaders(headers,isAdmin=false){headers.set('X-Frame-Options','DENY');headers.set('X-Content-Type-Options','nosniff');headers.set('Referrer-Policy','no-referrer');headers.set('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(), usb=()');headers.set('Cross-Origin-Opener-Policy','same-origin');headers.set('Strict-Transport-Security','max-age=31536000; includeSubDomains');headers.set('X-Robots-Tag',isAdmin?'noindex, nofollow, noarchive':'index, follow');if(isAdmin)headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; connect-src 'self' https://nbsmkxarkpesjiftmbwm.supabase.co; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; font-src 'self' https: data:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'")}
function redirectToLogin(request){const url=new URL(request.url);const next=encodeURIComponent(url.pathname+url.search);return new Response(null,{status:302,headers:{Location:`/admin.html?next=${next}`,'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','X-Content-Type-Options':'nosniff'}})}
async function getAdminUser(accessToken){if(!accessToken)return null;const a=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`}});if(!a.ok)return null;const user=await a.json();if(!user?.id||user.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase())return null;const p=await fetch(`${SUPABASE_URL}/rest/v1/profiles?select=role&id=eq.${encodeURIComponent(user.id)}&limit=1`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`}});if(!p.ok)return null;const profiles=await p.json();return profiles?.[0]?.role==='admin'?user:null}
async function refreshSession(refreshToken){if(!refreshToken)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({refresh_token:refreshToken})});if(!r.ok)return null;const d=await r.json();if(!d?.access_token||!d?.refresh_token)return null;return await getAdminUser(d.access_token)?d:null}
async function createAdminSession(request){if(request.method!=='POST')return new Response('Method Not Allowed',{status:405,headers:{Allow:'POST, DELETE','Cache-Control':'no-store'}});const origin=request.headers.get('Origin');if(origin&&origin!==new URL(request.url).origin)return new Response(JSON.stringify({ok:false,error:'Forbidden origin'}),{status:403,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});const a=request.headers.get('Authorization')||'';const token=a.startsWith('Bearer ')?a.slice(7).trim():'';const refreshToken=request.headers.get('X-Admin-Refresh-Token')||'';const user=await getAdminUser(token);if(!user||!refreshToken)return new Response(JSON.stringify({ok:false,error:'Unauthorized'}),{status:401,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});const response=new Response(JSON.stringify({ok:true,email:user.email}),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});response.headers.append('Set-Cookie',cookie(ACCESS_COOKIE,token,ACCESS_MAX_AGE));response.headers.append('Set-Cookie',cookie(REFRESH_COOKIE,refreshToken,REFRESH_MAX_AGE));return response}
function clearAdminSession(){const response=new Response(JSON.stringify({ok:true}),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});response.headers.append('Set-Cookie',clearCookie(ACCESS_COOKIE));response.headers.append('Set-Cookie',clearCookie(REFRESH_COOKIE));return response}
async function protectAdminPage(request,env){const cookies=parseCookies(request);let accessToken=cookies[ACCESS_COOKIE],refreshToken=cookies[REFRESH_COOKIE],refreshed=null,user=await getAdminUser(accessToken);if(!user&&refreshToken){refreshed=await refreshSession(refreshToken);if(refreshed){accessToken=refreshed.access_token;refreshToken=refreshed.refresh_token;user=await getAdminUser(accessToken)}}if(!user)return redirectToLogin(request);const response=await env.ASSETS.fetch(request);const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;const headers=new Headers(response.headers);headers.set('Content-Type','text/html; charset=UTF-8');headers.set('Cache-Control','private, no-store, max-age=0, must-revalidate');securityHeaders(headers,true);if(refreshed){headers.append('Set-Cookie',cookie(ACCESS_COOKIE,accessToken,ACCESS_MAX_AGE));headers.append('Set-Cookie',cookie(REFRESH_COOKIE,refreshToken,REFRESH_MAX_AGE))}const url=new URL(request.url);if(url.pathname.startsWith('/admin-dashboard')){const html=await response.text();let injected=html;
// Keep the dashboard boot chain in one place. The finance base loader then loads
// the single current finance UI (V2) and its CRUD helpers. The older finance
// hotfixes are intentionally NOT injected here because they rendered duplicate
// income/expense lists on top of the editable drill-down list.
if(!injected.includes('admin-motor-catalog-hotfix.js'))injected=injected.replace('</body>','<script src="./admin-motor-catalog-hotfix.js?v=20260816-catalog2"></script>\n</body>');
if(!injected.includes('admin-finance-base-loader-hotfix.js'))injected=injected.replace('</body>','<script src="./admin-finance-base-loader-hotfix.js?v=20260817-financebase3"></script>\n</body>');
return new Response(injected,{status:response.status,statusText:response.statusText,headers})}return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
async function servePublic(request,env){const response=await env.ASSETS.fetch(request);const type=response.headers.get('content-type')||'';const url=new URL(request.url);if(!type.includes('text/html')||url.pathname.startsWith('/admin'))return response;const headers=new Headers(response.headers);headers.set('Content-Type','text/html; charset=UTF-8');headers.set('Cache-Control','no-store, max-age=0, must-revalidate');securityHeaders(headers,false);if(url.pathname==='/'||url.pathname==='/index.html'){const html=await response.text();if(!html.includes('public-sync-v3.js')){const injected=html.replace('</body>','<script src="./public-sync-v3.js"></script>\n</body>');return new Response(injected,{status:response.status,statusText:response.statusText,headers})}return new Response(html,{status:response.status,statusText:response.statusText,headers})}return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/admin-session'){if(request.method==='POST')return createAdminSession(request);if(request.method==='DELETE')return clearAdminSession();return new Response('Method Not Allowed',{status:405,headers:{Allow:'POST, DELETE','Cache-Control':'no-store'}})}const protectedAdmin=url.pathname==='/admin-dashboard'||url.pathname==='/admin-dashboard.html'||url.pathname.startsWith('/admin-dashboard-')||url.pathname.startsWith('/admin-dashboard/');if(protectedAdmin)return protectAdminPage(request,env);if(url.pathname.startsWith('/admin')){const response=await env.ASSETS.fetch(request);const headers=new Headers(response.headers);securityHeaders(headers,true);headers.set('Cache-Control','no-store, max-age=0, must-revalidate');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}return servePublic(request,env)}}